openapi: 3.0.3
info:
  version: 1.0.0
  title: Tiny URL API
  contact:
    email: aleksandra.200328@gmail.com
servers:
  - url: localhost:8080
paths:
  /add:
    post:
      summary: Generate short URL
      tags:
        - "URL"
      requestBody:
        description: Generate and save URL
        content:
          application/json:
            schema: 
              type: object
              required:
                - "url"
              properties:
                url:
                  type: string
                  example: https://go.dev
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                    example: qwerty
                    nullable: false
        "400":
          description: Bad Request Error
        "500":
          description: Internal Server Error
  /:shortUrl:
    get:
      summary: URL forward
      tags:
        - "URL"
      parameters:
        - name: shortUrl
          in: path
          description: Generated token
          required: true
          schema:
            type: string
      responses:
        "302":
          description: Success
        "400":
          description: Bad Request Error
        "404":
          description: Not Found Error
        "500":
          description: Internal Server Error